'use strict';
// All alternative activities assess the same sourced concepts as their questions.
const activities={
 2:{type:'sort',prompt:'Sort these fats by the type of fat they contain most.',items:['Butter','Olive oil','Safflower oil'],targets:['Mostly unsaturated','Mostly saturated'],key:[1,0,0]},
 4:{type:'order',prompt:'Rank these foods from least to most cholesterol per gram of edible food.',items:['Ground beef patty (90% lean, broiled)','Apple (raw, with skin)','Chicken leg (meat and skin, roasted)','White tuna (canned in oil, drained)','Turkey breast (meat only, roasted)'],key:[1,3,4,0,2],ranking:true},
 7:{type:'order',prompt:'Build a three-step game plan for food shopping on a budget.',items:['Prepare','Purchase','Plan'],key:[2,1,0]},
 9:{type:'sort',prompt:'Supermarket challenge: sort each product by its main grain ingredient.',items:['RITZ Original Crackers','Original Cheerios','Kellogg’s Rice Krispies cereal','Triscuit Original Crackers'],targets:['Main grain is whole grain','Main grain is refined grain'],key:[1,0,1,0]},
 12:{type:'number',prompt:'Read the label. How much sodium is in two servings?',answer:300,min:0,max:1200,step:10,label:'Total sodium'},
 13:{type:'number',prompt:'After a sugary snack, about how many minutes can a plaque-acid attack last? Set the clock to the approximate duration used in ADA classroom guidance.',answer:20,min:0,max:60,step:5,label:'Acid-attack duration',unit:'minutes',clock:true},
 15:{type:'circle',prompt:'You use 150 g of the raw ground beef shown. About how many grams of fat does that portion contain?',items:['15 g','30 g','120 g'],key:[1],image:true},
 18:{type:'number',prompt:'Set the daily sodium limit in FDA guidance for people age 14 and older. The guidance is to stay below this amount.',answer:2300,min:0,max:5000,step:100,label:'Daily sodium limit'},
 19:{type:'circle',prompt:'Circle two salad additions that supply mostly unsaturated fat.',items:['Walnuts','Butter','Olive oil'],icons:['🥜','🧈','🫒'],key:[0,2]}
};
let activityState={placements:{},order:[],active:null,value:'',circled:[]};
function resetActivity(){activityState={placements:{},order:[],active:null,value:'',circled:[]};}
function activityReady(q){const a=activities[q.id];if(!a)return selected.size>0;if(a.type==='order')return activityState.order.length===a.items.length;if(a.type==='number'){const n=Number(activityState.value);return /^\d+$/.test(activityState.value)&&n>=a.min&&n<=a.max&&n%a.step===0;}if(a.type==='circle')return activityState.circled.length===a.key.length;return Object.keys(activityState.placements).length===a.items.length;}
function activityCorrect(q){const a=activities[q.id];if(!a)return selected.size===q.correct.length&&q.correct.every(i=>selected.has(i));if(a.type==='number')return Number(activityState.value)===a.answer;if(a.type==='order')return a.key.every((n,i)=>activityState.order[i]===n);if(a.type==='circle')return a.key.length===activityState.circled.length&&a.key.every(n=>activityState.circled.includes(n));return a.key.every((n,i)=>activityState.placements[i]===n);}
function activitySummary(q,solution=false){const a=activities[q.id];if(!a)return q.correct.map(i=>q.options[i]).join(' + ');if(a.type==='number')return (solution?a.answer:activityState.value)+(a.unit?' '+a.unit:q.id===18?' mg sodium per day (stay below this limit)':' mg sodium');if(a.type==='order')return (solution?a.key:activityState.order).map(i=>a.items[i]).join(' → ');if(a.type==='circle')return (solution?a.key:activityState.circled).map(i=>a.items[i]).join(' + ');return a.items.map((name,i)=>name+' → '+a.targets[solution?a.key[i]:activityState.placements[i]]).join('; ');}
function activityInstruction(q){const a=activities[q.id];if(!a)return q.interaction==='dial'?'Slide or tap to choose your answer.':q.correct.length>1?'Choose two answers.':'Pick the answer you think fits best.';return {sort:'Tap a food, then its group. You can also drag it. Tap a placed food to move it.',connect:'Tap a food on the left, then its match on the right. Tap a food again to change its connection.',order:a.ranking?'Rank from lowest at 1 to highest at 5. Compare equal food weights, not typical portions. Tap cards in order; use the move buttons to rearrange.':'Tap the cards in order. Tap a numbered card to put it back, or use its move buttons.',number:a.clock?'Drag the clock hand, tap the clock face, or use the slider. The estimate is approximate.':`Slide to your answer, fine-tune with the buttons, or type a number. Steps of ${a.step} ${a.unit||'mg'}.`,circle:`Tap to circle ${a.key?.length===2?'two answers':'one answer'}. Tap again to unselect.`}[a.type];}
function numberControls(q){const a=activities[q.id],value=activityState.value,valid=activityReady(q),n=valid?Number(value):a.min,disabled=checked?'disabled':'';return `<div class="number-game"><label class="number-title" for="answer-slider">${esc(a.label)}</label><div class="slider-readout"><output id="slider-readout" for="answer-slider number-answer">${value===''?'—':esc(value)}</output><span>${a.unit||'mg'}</span></div><p class="slider-status" id="slider-status">${value===''?'Move the slider to make your estimate.':valid?'Your estimate is ready to lock in.':`Enter ${a.min}–${a.max} ${a.unit||'mg'} in steps of ${a.step}.`}</p><input class="answer-slider" id="answer-slider" type="range" min="${a.min}" max="${a.max}" step="${a.step}" value="${n}" aria-valuetext="${value===''?'No answer selected':n+' '+(a.unit||'milligrams')}" aria-describedby="slider-status" style="--fill:${(n-a.min)/(a.max-a.min)*100}%" ${disabled}><div class="slider-scale"><span>${a.min} ${a.unit||'mg'}</span><span>${a.max/2} ${a.unit||'mg'}</span><span>${a.max} ${a.unit||'mg'}</span></div><div class="number-adjust"><button type="button" data-nudge="-1" aria-label="Decrease by ${a.step} ${a.unit||'milligrams'}" ${disabled}>−${a.step}</button><div><label for="number-answer">Or type your estimate</label><div class="number-wrap"><input id="number-answer" type="number" inputmode="numeric" min="${a.min}" max="${a.max}" step="${a.step}" value="${esc(value)}" aria-describedby="slider-status" ${disabled} autocomplete="off"><span>${a.unit||'mg'}</span></div></div><button type="button" data-nudge="1" aria-label="Increase by ${a.step} ${a.unit||'milligrams'}" ${disabled}>+${a.step}</button></div></div>`;}
function updateNumber(q,value){if(checked)return;activityState.value=value;const a=activities[q.id],valid=activityReady(q),slider=document.getElementById('answer-slider'),field=document.getElementById('number-answer');if(field)field.value=value;if(slider){slider.value=valid?value:a.min;slider.setAttribute('aria-valuetext',valid?value+' '+(a.unit||'milligrams'):'No valid estimate selected');slider.style.setProperty('--fill',valid?(Number(value)-a.min)/(a.max-a.min)*100+'%':'0%');}document.getElementById('slider-readout').textContent=value===''?'—':value;document.getElementById('slider-status').textContent=value===''?'Move the slider to make your estimate.':valid?'Your estimate is ready to lock in.':`Enter ${a.min}–${a.max} ${a.unit||'mg'} in steps of ${a.step}.`;const face=document.getElementById('guess-clock');if(face){face.setAttribute('aria-valuenow',valid?value:0);face.setAttribute('aria-valuetext',valid?value+' minutes':'No answer selected');document.getElementById('clock-hand').setAttribute('transform',`rotate(${valid?Number(value)*6:0} 120 120)`);}document.getElementById('submit').disabled=!valid;}
function activityControls(q){const a=activities[q.id],s=activityState,disabled=checked?'disabled':'';
 const item=(i,extra='')=>`<button type="button" class="activity-card ${s.active===i?'picked':''}" data-item="${i}" draggable="${!checked}" aria-pressed="${s.active===i}" ${disabled} ${extra}>${esc(a.items[i])}</button>`;
 if(a.type==='sort')return `<div class="activity sort-activity"><div class="card-bank" aria-label="Unsorted foods">${a.items.map((_,i)=>s.placements[i]===undefined?item(i):'').join('')||'<span class="bank-empty">All cards placed. Check your groups below.</span>'}</div><div class="sort-bins">${a.targets.map((target,t)=>`<div class="sort-bin" data-drop="${t}"><button class="bin-target" data-target="${t}" ${disabled}>${esc(target)}<span>${s.active!==null?'Place selected food here':'Select a food first'}</span></button><div class="placed-cards">${a.items.map((_,i)=>s.placements[i]===t?item(i):'').join('')}</div></div>`).join('')}</div><p class="activity-count">${Object.keys(s.placements).length} of ${a.items.length} sorted</p></div>`;
 if(a.type==='connect')return `<div class="activity"><div class="connect-board"><div class="connect-column">${a.items.map((_,i)=>`<button class="activity-card ${s.active===i?'picked':''}" data-item="${i}" aria-pressed="${s.active===i}" ${disabled}><b>${i+1}</b> ${esc(a.items[i])}<small>${s.placements[i]!==undefined?'Connected to '+String.fromCharCode(65+s.placements[i]):'Not connected'}</small></button>`).join('')}</div><svg class="connection-lines" viewBox="0 0 100 200" preserveAspectRatio="none" aria-hidden="true">${Object.entries(s.placements).map(([i,t])=>`<line x1="0" y1="${Number(i)*100+50}" x2="100" y2="${t*100+50}" stroke="${Number(i)===0?'#245e90':'#744e9d'}" stroke-width="4"/>`).join('')}</svg><div class="connect-column">${a.targets.map((t,i)=>`<button class="activity-card connection-target" data-target="${i}" ${disabled}><b>${String.fromCharCode(65+i)}</b> ${esc(t)}</button>`).join('')}</div></div><p class="activity-count" aria-live="polite">${Object.keys(s.placements).length} of ${a.items.length} connected</p></div>`;
 if(a.type==='order')return `<div class="activity"><ol class="order-slots">${Array.from({length:a.items.length},(_,slot)=>`<li><span class="slot-number">${slot+1}</span>${s.order[slot]===undefined?`<span class="empty-slot">${a.ranking?'Choose the next food below':'Choose the next step below'}</span>`:`<button class="ordered-text" data-remove="${slot}" ${disabled} aria-label="Remove step ${slot+1}: ${esc(a.items[s.order[slot]])}">${esc(a.items[s.order[slot]])}</button><div class="move-controls"><button data-move="${slot},-1" ${checked||slot===0?'disabled':''} aria-label="Move step ${slot+1} earlier">↑</button><button data-move="${slot},1" ${checked||slot===s.order.length-1?'disabled':''} aria-label="Move step ${slot+1} later">↓</button></div>`}</li>`).join('')}</ol><div class="card-bank">${a.items.map((_,i)=>!s.order.includes(i)?item(i):'').join('')}</div></div>`;
 if(a.clock)return `<div class="activity clock-activity"><svg id="guess-clock" class="guess-clock" viewBox="0 0 240 240" role="slider" tabindex="${checked?'-1':'0'}" aria-label="Minutes of acid attack; use arrow keys or drag the hand" aria-valuemin="0" aria-valuemax="60" aria-valuenow="${s.value||0}" aria-valuetext="${s.value?s.value+' minutes':'No answer selected'}" aria-disabled="${checked}"><circle cx="120" cy="120" r="112" fill="#f4faff" stroke="#244b7c" stroke-width="5"/>${Array.from({length:12},(_,i)=>{const angle=i*Math.PI/6;return `<text x="${120+92*Math.sin(angle)}" y="${125-92*Math.cos(angle)}" text-anchor="middle" font-size="15" fill="#244b7c">${i*5}</text>`;}).join('')}<text x="120" y="160" text-anchor="middle" font-size="11" fill="#526b83">MINUTES</text><g id="clock-hand" transform="rotate(${Number(s.value||0)*6} 120 120)"><line x1="120" y1="132" x2="120" y2="48" stroke="#245e90" stroke-width="7" stroke-linecap="round"/><circle cx="120" cy="48" r="11" fill="#62a5df" stroke="#244b7c" stroke-width="3"/></g><circle cx="120" cy="120" r="9" fill="#244b7c"/></svg>${numberControls(q)}</div>`;
 if(a.type==='number'&&q.id===18)return `<div class="activity sodium-slider-activity"><span class="eyebrow">Set your estimate</span>${numberControls(q)}</div>`;
 if(a.type==='number')return `<div class="activity label-calculation full-label-activity"><div class="product-panel"><div class="product-heading"><span class="product-brand">TRAILSIDE</span><h2>Baked Crackers</h2><p>Sea Salt · Net wt 8.5 oz (240 g)</p></div><div class="nutrition-label full-nutrition-label" aria-label="Trailside Sea Salt Baked Crackers Nutrition Facts"><h2>Nutrition Facts</h2><div class="nf-servings">8 servings per container</div><div class="nf-serving"><b>Serving size</b><b>15 crackers (30 g)</b></div><div class="nf-calories"><span><small>Amount per serving</small><b>Calories</b></span><strong>130</strong></div><div class="nf-dv">% Daily Value*</div><table class="nf-table"><caption class="sr-only">Nutrients per serving and percent Daily Value</caption><tbody><tr><th scope="row"><b>Total Fat</b> 4g</th><td>5%</td></tr><tr><th scope="row" class="nf-indent">Saturated Fat 0.5g</th><td>3%</td></tr><tr><th scope="row" class="nf-indent"><i>Trans</i> Fat 0g</th><td></td></tr><tr><th scope="row"><b>Cholesterol</b> 0mg</th><td>0%</td></tr><tr><th scope="row"><b>Sodium</b> 150mg</th><td>7%</td></tr><tr><th scope="row"><b>Total Carbohydrate</b> 21g</th><td>8%</td></tr><tr><th scope="row" class="nf-indent">Dietary Fiber 2g</th><td>7%</td></tr><tr><th scope="row" class="nf-indent">Total Sugars 1g</th><td></td></tr><tr><th scope="row" class="nf-double-indent">Includes 0g Added Sugars</th><td>0%</td></tr><tr class="nf-protein"><th scope="row"><b>Protein</b> 3g</th><td></td></tr><tr><th scope="row">Vitamin D 0mcg</th><td>0%</td></tr><tr><th scope="row">Calcium 20mg</th><td>2%</td></tr><tr><th scope="row">Iron 1mg</th><td>6%</td></tr><tr><th scope="row">Potassium 60mg</th><td>2%</td></tr></tbody></table><div class="nf-footnote">* The % Daily Value (DV) tells you how much a nutrient in a serving of food contributes to a daily diet. 2,000 calories a day is used for general nutrition advice.</div></div><div class="product-ingredients"><b>INGREDIENTS:</b> Whole wheat flour, wheat flour, sunflower oil, salt, yeast, malted barley flour.<br><b>CONTAINS: WHEAT.</b></div><p class="practice-note">Fictional product · Practice label</p></div><div class="calculation"><span class="portion-count">You ate 2 servings (30 crackers)</span>${numberControls(q)}<p class="label-task-note">Use the label to find how much sodium you ate.</p></div></div>`;
 if(a.type==='circle')return `<div class="activity ${a.label?'package-activity':'salad-activity'}">${a.image?'<figure class="beef-photo"><img src="assets/beef-package.png" alt="Ground beef package labeled 80% lean and 20% fat"><figcaption>Illustrative package · raw product</figcaption></figure>':a.label?'<span class="package-heading">GROUND BEEF</span><p>Read the package. Circle the fat percentage.</p>':'<div class="salad-heading">Build your salad</div>'}<div class="circle-items">${a.items.map((text,i)=>`<button class="circle-item ${s.circled.includes(i)?'circled':''}" data-circle="${i}" aria-pressed="${s.circled.includes(i)}" ${disabled}>${a.icons?`<span class="food" aria-hidden="true">${a.icons[i]}</span>`:''}<strong>${esc(text)}</strong>${a.label?`<small>${['LEAN','PORTION WEIGHT','FAT'][i]}</small>`:''}<span class="circle-mark" aria-hidden="true">${s.circled.includes(i)?'✓':'○'}</span></button>`).join('')}</div><p class="activity-count">${s.circled.length} of ${a.key.length} circled</p></div>`;
}
function activityRefresh(selector){render();if(selector)app.querySelector(selector)?.focus();}
function pickItem(i){if(checked)return;const a=activities[current().id];if(a.type==='order'){if(!activityState.order.includes(i))activityState.order.push(i);activityRefresh(`[data-remove="${activityState.order.length-1}"]`);}else{activityState.active=activityState.active===i?null:i;activityRefresh(`[data-item="${i}"]`);}}
function placeItem(target){if(checked||activityState.active===null)return;const a=activities[current().id],i=activityState.active;if(a.type==='connect'){for(const [key,value] of Object.entries(activityState.placements))if(value===target)delete activityState.placements[key];}activityState.placements[i]=target;activityState.active=null;activityRefresh(`[data-target="${target}"]`);}
function bindActivity(q){const a=activities[q.id];if(!a)return;
 app.querySelectorAll('[data-item]').forEach(b=>{b.addEventListener('click',()=>pickItem(Number(b.dataset.item)));b.addEventListener('dragstart',e=>{if(checked){e.preventDefault();return;}activityState.active=Number(b.dataset.item);e.dataTransfer.setData('text/plain',b.dataset.item);});});
 app.querySelectorAll('[data-target]').forEach(b=>b.addEventListener('click',()=>placeItem(Number(b.dataset.target))));
 app.querySelectorAll('[data-drop]').forEach(b=>{b.addEventListener('dragover',e=>{if(!checked)e.preventDefault();});b.addEventListener('drop',e=>{e.preventDefault();if(checked)return;const raw=e.dataTransfer.getData('text/plain');if(!/^\d+$/.test(raw)||Number(raw)>=a.items.length)return;activityState.active=Number(raw);placeItem(Number(b.dataset.drop));});});
 app.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{if(checked)return;activityState.order.splice(Number(b.dataset.remove),1);activityRefresh('.card-bank button');}));
 app.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('click',()=>{if(checked)return;const [i,delta]=b.dataset.move.split(',').map(Number),j=i+delta;if(j<0||j>=activityState.order.length)return;[activityState.order[i],activityState.order[j]]=[activityState.order[j],activityState.order[i]];activityRefresh(`[data-remove="${j}"]`);}));
 app.querySelectorAll('[data-circle]').forEach(b=>b.addEventListener('click',()=>{if(checked)return;const i=Number(b.dataset.circle),s=activityState;s.circled=s.circled.includes(i)?s.circled.filter(n=>n!==i):a.key.length===1?[i]:s.circled.length<a.key.length?[...s.circled,i]:s.circled;activityRefresh(`[data-circle="${i}"]`);}));
 if(a.clock){const clock=document.getElementById('guess-clock');let dragging=false;const point=e=>{if(checked)return;const box=clock.getBoundingClientRect(),x=e.clientX-box.left-box.width/2,y=e.clientY-box.top-box.height/2;const degrees=(Math.atan2(x,-y)*180/Math.PI+360)%360;updateNumber(q,String(Math.round(degrees/6/a.step)*a.step));};clock.addEventListener('pointerdown',e=>{if(checked)return;e.preventDefault();clock.focus();dragging=true;clock.setPointerCapture(e.pointerId);point(e);});clock.addEventListener('pointermove',e=>{if(dragging)point(e);});clock.addEventListener('pointerup',()=>dragging=false);clock.addEventListener('pointercancel',()=>dragging=false);clock.addEventListener('keydown',e=>{if(checked)return;let n=Number(activityState.value||0);if(['ArrowRight','ArrowUp'].includes(e.key))n+=a.step;else if(['ArrowLeft','ArrowDown'].includes(e.key))n-=a.step;else if(e.key==='Home')n=a.min;else if(e.key==='End')n=a.max;else return;e.preventDefault();updateNumber(q,String(Math.max(a.min,Math.min(a.max,n))));});}
 if(a.type==='number'){
 const field=document.getElementById('number-answer'),slider=document.getElementById('answer-slider');
 field?.addEventListener('input',()=>updateNumber(q,field.value));
 slider?.addEventListener('input',()=>updateNumber(q,slider.value));
 app.querySelectorAll('[data-nudge]').forEach(b=>b.addEventListener('click',()=>{const base=activityReady(q)?Number(activityState.value):a.min;updateNumber(q,String(Math.max(a.min,Math.min(a.max,base+Number(b.dataset.nudge)*a.step))));}));
 }
}
