'use strict';
const questions=window.QUIZ_QUESTIONS;
const topics=['Fats & fuel','Fats & fuel','Food comparisons','Food comparisons','Hydration myth-buster','Food & balance','Smart shopping','Science & risk','Grain game','Carbohydrates','Workout fuel','Label detective','Sugar & smiles','Supplement science','Label detective','Protein power','Food & vision','Salt sense','Salad challenge','The big picture'];
const icons=[['🫒','🥥','🌴','🥩'],['🌻','🫒','🧈'],['🥚','🥜','🥩'],['🦐','🐟','🍎'],['☕','💧','🚰'],['🍌','🍅','🫘','✨'],['🛒','📋','🥣'],['①','②','③'],['🌾','🌾','🍘'],['⚖️','📈','🍽️','📊'],['🥯','🥜','🍚','🍌'],['①','②','③'],['🦷','🔬','⏱️'],['🔬','👥','📊','⚙️'],['⑤','⑮','⑳'],['🧬','⚡','🧪','💪'],['🥬','🐟','🍅'],['🧂','🧂','🧂'],['🥜','🧈','🫒'],['🔺','🍽️','📂','🍽️']];
let queue=questions.map((_,i)=>i),position=0,phase='quest',selected=new Set(),answers=[],mastered=new Set(),checked=false,reviewOpen=false,xp=0,streak=0,bestStreak=0,lastResult=null;
const app=document.getElementById('app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const score=()=>answers.filter(a=>a?.correct).length;
const current=()=>questions[queue[position]];
const badges=()=>[{name:'First five',icon:'✦',earned:answers.filter(Boolean).length>=5,rule:'Explore 5 questions'},{name:'On a roll',icon:'⚡',earned:bestStreak>=3,rule:'Get 3 correct in a row on your first run'},{name:'Finish strong',icon:'🏁',earned:answers.filter(Boolean).length===20,rule:'Complete all 20 challenges'},{name:'Full plate',icon:'🏆',earned:mastered.size===20,rule:'Master all 20, including comebacks'}];
function badgeHTML(){return `<div class="badges">${badges().map(b=>`<div class="badge ${b.earned?'earned':''}"><span aria-hidden="true">${b.icon}</span><strong>${b.name}</strong><small>${b.earned?'Unlocked · ':''}${b.rule}</small></div>`).join('')}</div>`;}
function science(q){return `<div class="science"><h3>The science behind it</h3><p>${esc(q.explanation)}</p><details><summary>Explore the evidence (${q.sources.length})</summary><ul>${q.sources.map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)} <span class="sr-only">(opens in a new tab)</span></a></li>`).join('')}</ul></details></div>`;}
function progressPanel(){return `<details class="progress-panel"><summary><span><b>${mastered.size} / 20</b> mastered</span><span>${badges().filter(b=>b.earned).length} / 4 badges <span aria-hidden="true">⌄</span></span></summary><div class="progress-panel-content"><div><h3>Question history</h3><div class="dots">${questions.map((q,i)=>`<span class="dot ${i===queue[position]?'active':mastered.has(i)?'done':answers[i]?'missed':''}" aria-label="Question ${i+1}: ${mastered.has(i)?'mastered':i===queue[position]?'current':answers[i]?'try again':'upcoming'}">${mastered.has(i)?'✓':i+1}</span>`).join('')}</div><p class="legend">Blue: mastered · Peach: try again · Outline: current</p><h3>How points work</h3><p>20 XP per first attempt, plus 80 for correct answers. Every 3-answer streak adds 25 XP. Comebacks earn 40 XP once per newly mastered question. Your first-run score stays the same.</p></div>${badgeHTML()}</div></details>`;}
function render(focus=false){
 if(position>=queue.length){renderResults();return;}
 const q=current(),multi=q.correct.length>1,dial=q.interaction==='dial';
 let controls;
 if(activities[q.id])controls=activityControls(q);
 else if(dial){const val=selected.size?[...selected][0]:1;controls=`<div class="dial"><div class="dial-value"><span id="dial-value">${q.values[val]}%</span><small>${esc(q.unit)}</small></div><label for="dial-answer">Slide to the percentage on the label</label><br><input id="dial-answer" type="range" min="0" max="${q.values.length-1}" step="1" value="${val}" aria-valuetext="${q.values[val]} percent fat" ${checked?'disabled':''}><div class="ticks">${q.values.map(v=>`<span>${v}%</span>`).join('')}</div><div class="dial-options" role="group" aria-label="Or tap a percentage">${q.options.map((v,i)=>`<button data-choice="${i}" aria-pressed="${selected.has(i)}" ${checked?'disabled':''}>${esc(v)}</button>`).join('')}</div></div>`;}
 else controls=`<div class="choices ${q.id===7?'sequence':''}" role="group" aria-label="Answer choices">${q.options.map((o,i)=>`<button class="choice ${selected.has(i)?'selected':''} ${checked?(q.correct.includes(i)?'correct':selected.has(i)?'wrong':''):''}" data-choice="${i}" aria-pressed="${selected.has(i)}" ${checked?'disabled':''}><span class="food" aria-hidden="true">${icons[q.id-1][i]}</span><span class="answer-text">${q.id===7?o.split(', ').map((s,k)=>`<span class="step">${k+1}. ${esc(s)}</span>`).join(''):esc(o)}</span><span class="key" aria-hidden="true">${checked&&q.correct.includes(i)?'✓':selected.has(i)?'●':i+1}</span></button>`).join('')}</div>`;
 app.innerHTML=gameHTML()+`<div class="challenge-overlay" ${game.quizOpen?'':'hidden'}><div class="challenge-dialog" id="challenge-dialog" role="dialog" aria-modal="true" aria-label="Nutrition challenge"><button class="close-challenge secondary" id="close-challenge">Back to board</button><div class="topline"><span class="eyebrow">${phase==='quest'?'FOOD FOR THOUGHT':'COMEBACK ROUND'} · ${position+1} / ${queue.length}</span><div class="stats"><span class="pill">✦ <b>${xp}</b> XP</span><span class="pill">⚡ <b>${streak}</b> streak</span></div></div><div class="progress" role="progressbar" aria-label="Round progress" aria-valuemin="0" aria-valuemax="${queue.length}" aria-valuenow="${position+(checked?1:0)}"><div style="width:${(position+(checked?1:0))/queue.length*100}%"></div></div>${progressPanel()}<div class="layout"><section><span class="eyebrow">${esc(topics[q.id-1])}</span><h1 tabindex="-1">${esc(activities[q.id]?.prompt||q.prompt)}</h1><p class="instruction">${activityInstruction(q)}</p>${controls}<div id="feedback" aria-live="polite">${checked?feedback(q):''}</div><div class="actions"><button class="primary" id="submit" ${!checked&&!activityReady(q)?'disabled':''}>${checked?('Use earned moves'):'Lock in answer'}</button><span class="hint">${activities[q.id]?'Use touch, mouse, or Tab and Enter.':`Tap an answer or press 1–${q.options.length}.`}</span></div></section></div></div></div>`;
 app.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>choose(Number(b.dataset.choice))));
 const slider=document.getElementById('dial-answer');if(slider)slider.addEventListener('input',()=>{selected=new Set([Number(slider.value)]);document.getElementById('dial-value').textContent=q.values[slider.value]+'%';slider.setAttribute('aria-valuetext',`${q.values[slider.value]} percent fat`);app.querySelectorAll('[data-choice]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.choice)===Number(slider.value)));document.getElementById('submit').disabled=false;});
 bindActivity(q);
 bindGame();
 document.getElementById('submit').addEventListener('click',submit);
 if(focus)app.querySelector(game.quizOpen?'#challenge-dialog h1':'#game-title')?.focus();
}
function choose(i){if(checked||position>=queue.length)return;const q=current();if(activities[q.id])return;if(q.correct.length>1){if(selected.has(i))selected.delete(i);else selected.add(i);}else selected=new Set([i]);render();app.querySelector(`[data-choice="${i}"]`)?.focus();}
function feedback(q){return `<div class="feedback ${lastResult.correct?'':'miss'}" tabindex="-1"><strong>${lastResult.correct?'You’ve got it!':'Keep going—this one is worth learning.'} <span class="xp-gain">+${lastResult.gain} XP · +${lastResult.moveReward} moves</span></strong><p><b>Correct ${activities[q.id]?.ranking?'order':q.correct.length>1?'answers':'answer'}:</b> ${esc(activitySummary(q,true))}</p>${science(q)}</div>`;}
function submit(){
 if(checked){game.quizOpen=false;position++;selected=new Set();resetActivity();checked=false;render(true);return;}
 if(position>=queue.length||!activityReady(current()))return;
 const q=current(),id=queue[position],correct=activityCorrect(q);let gain=0;
 if(phase==='quest'){streak=correct?streak+1:0;bestStreak=Math.max(bestStreak,streak);gain=20+(correct?80:0)+(correct&&streak%3===0?25:0);answers[id]={selected:[...selected],correct,response:activities[q.id]?activitySummary(q):[...selected].map(i=>q.options[i]).join(' + ')};}
 else if(correct&&!mastered.has(id))gain=40;
 const moveReward=awardMoves(correct,id);if(correct)mastered.add(id);xp+=gain;lastResult={correct,gain,moveReward};checked=true;render();app.querySelector('.feedback').focus();if(correct)celebrate();
}
function celebrate(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<12;i++){const s=document.createElement('span');s.className='spark';s.textContent=['✦','✧','●'][i%3];s.style.color=['#62a5df','#87ceeb','#243962'][i%3];s.style.setProperty('--x',`${Math.cos(i/12*Math.PI*2)*220}px`);s.style.setProperty('--y',`${Math.sin(i/12*Math.PI*2)*220}px`);s.setAttribute('aria-hidden','true');document.body.append(s);setTimeout(()=>s.remove(),1000);}}
function restart(){resetGame();queue=questions.map((_,i)=>i);position=0;phase='quest';selected=new Set();resetActivity();answers=[];mastered=new Set();checked=false;reviewOpen=false;xp=0;streak=0;bestStreak=0;lastResult=null;render(true);}
function comeback(){game.quizOpen=true;queue=questions.map((_,i)=>i).filter(i=>!mastered.has(i));position=0;phase='comeback';selected=new Set();resetActivity();checked=false;reviewOpen=false;streak=0;render(true);}
function renderResults(){const missed=questions.length-mastered.size;app.innerHTML=gameHTML()+`<section class="result"><img class="result-logo" src="assets/lc-logo.png" alt="Little Chute"><span class="eyebrow">${missed?'ROUND COMPLETE':'ALL 20 MASTERED'}</span><h1 tabindex="-1">${missed?'Ready for another bite?':'Food for thought. All figured out.'}</h1><div class="big-score">${score()}<small> / 20</small></div><p>First-run score · <b>${xp} XP</b> · Best streak: ${bestStreak}</p><p>${mastered.size} of 20 mastered${phase==='comeback'?' including comeback answers':''}. ${missed?'Read the explanations, then give missed questions another shot.':'All 20 challenges completed.'}</p>${badgeHTML()}<div class="actions">${missed?`<button class="primary" id="comeback">Comeback challenge (${missed})</button>`:''}<button class="secondary" id="review" aria-expanded="${reviewOpen}">${reviewOpen?'Hide answer review':'Review answers & science'}</button><button class="secondary" id="restart">Start a new round</button></div>${reviewOpen?`<div class="review">${questions.map((q,i)=>`<article class="review-item"><h3>${answers[i].correct?'✓':'↺'} ${i+1}. ${esc(activities[q.id]?.prompt||q.prompt)}</h3><p>First answer: ${esc(answers[i].response)}</p><p class="right">Correct answer: ${esc(activitySummary(q,true))}</p><p>${mastered.has(i)?'Mastered':'Comeback available'}</p>${science(q)}</article>`).join('')}</div>`:''}</section>`;document.getElementById('restart').onclick=restart;document.getElementById('comeback')?.addEventListener('click',comeback);document.getElementById('review').onclick=()=>{reviewOpen=!reviewOpen;renderResults();document.getElementById('review').focus();};bindGame();}
document.addEventListener('keydown',e=>{if(!game.quizOpen||position>=queue.length||checked||activities[current().id]||e.target.matches('input,summary,a'))return;const n=Number(e.key);if(Number.isInteger(n)&&n>=1&&n<=current().options.length){e.preventDefault();choose(n-1);}});
render();
