'use strict';
// Original match-three rules and visuals; no third-party game assets.
const treats=[{icon:'🍬',name:'wrapped candy'},{icon:'🍭',name:'lollipop'},{icon:'🍫',name:'chocolate'},{icon:'🍩',name:'donut'},{icon:'🍪',name:'cookie'}];
const SIZE=6;
let game={board:[],moves:0,points:0,swaps:0,selected:null,busy:false,quizOpen:false,message:'Answer a nutrition challenge to earn your first moves.',cleared:[],combo:0};
let gameEpoch=0;
function matchCells(board){const found=new Set();for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){const i=r*SIZE+c,v=board[i];if(v===null)continue;if(c<=SIZE-3&&v===board[i+1]&&v===board[i+2]){let k=c;while(k<SIZE&&board[r*SIZE+k]===v)found.add(r*SIZE+k++);}if(r<=SIZE-3&&v===board[i+SIZE]&&v===board[i+2*SIZE]){let k=r;while(k<SIZE&&board[k*SIZE+c]===v)found.add(k++*SIZE+c);}}return [...found];}
function adjacent(a,b){return Math.abs(a%SIZE-b%SIZE)+Math.abs(Math.floor(a/SIZE)-Math.floor(b/SIZE))===1;}
function legalSwap(board){for(let i=0;i<board.length;i++)for(const j of [i+1,i+SIZE]){if(j>=board.length||!adjacent(i,j))continue;[board[i],board[j]]=[board[j],board[i]];const has=matchCells(board).length>0;[board[i],board[j]]=[board[j],board[i]];if(has)return [i,j];}return null;}
function newBoard(){for(let attempt=0;attempt<100;attempt++){const b=[];for(let i=0;i<SIZE*SIZE;i++){const choices=[0,1,2,3,4].filter(v=>!(i%SIZE>=2&&b[i-1]===v&&b[i-2]===v)&&!(i>=SIZE*2&&b[i-SIZE]===v&&b[i-SIZE*2]===v));b.push(choices[Math.floor(Math.random()*choices.length)]);}if(legalSwap(b))return b;}const fallback=Array.from({length:36},(_,i)=>(i%6+2*Math.floor(i/6))%5);fallback[0]=0;fallback[1]=1;fallback[2]=0;fallback[7]=0;return fallback;}
function resetGame(){gameEpoch++;game={board:newBoard(),moves:0,points:0,swaps:0,selected:null,busy:false,quizOpen:false,message:'Answer a nutrition challenge to earn your first moves.',cleared:[],combo:0};}
function gameHTML(){if(!game.board.length)game.board=newBoard();const level=Math.floor(game.points/1000)+1,progress=game.points%1000;return `<section class="match-game" ${game.quizOpen?'inert aria-hidden="true"':''}><div class="game-title-row"><span class="eyebrow" tabindex="-1" id="game-title">MATCH • LEARN • REPEAT</span><span class="game-level">Level ${level}</span></div><div class="game-scorebar"><span><b>${game.points.toLocaleString()}</b> candy points</span><span><b>${game.moves}</b> moves left</span><span><b>${mastered.size}/20</b> mastered</span></div><div class="level-track" role="progressbar" aria-label="Candy points toward next level" aria-valuemin="0" aria-valuemax="1000" aria-valuenow="${progress}"><span style="width:${progress/10}%"></span></div><div class="game-stage"><div class="board-wrap"><div class="candy-board" role="group" aria-label="Candy match board, 6 rows and 6 columns">${game.board.map((v,i)=>`<button class="candy candy-${v} ${game.selected===i?'candy-selected':''} ${game.cleared.includes(i)?'candy-clearing':''}" data-cell="${i}" aria-label="Row ${Math.floor(i/SIZE)+1}, column ${i%SIZE+1}: ${treats[v]?.name||'empty'}" aria-pressed="${game.selected===i}" ${game.busy||game.moves===0?'disabled':''}><span aria-hidden="true">${treats[v]?.icon||''}</span></button>`).join('')}</div><p class="board-message" role="status">${esc(game.message)}</p></div><div class="game-coach"><h2>${game.moves?'Make your match.':'Unlock your next moves.'}</h2><p>Tap two neighboring treats to swap them. Match 3 or more in a row or column.</p><div class="move-rewards"><span><b>Correct</b> +3 moves</span><span><b>Learn from a miss</b> +1 move</span></div><p class="game-small">First run rewards. Master a missed question in a comeback for +2 moves. No timer, and swaps that make no match cost nothing.</p>${position<queue.length?`<button class="primary" id="open-challenge" ${game.busy?'disabled':''}>${checked?'Review answer & continue':`Answer challenge ${position+1}`}</button>`:'<p><b>All challenges in this round are complete.</b> Use your remaining moves, then review your results below.</p>'}<button class="secondary" id="board-hint" ${game.busy||!game.moves?'disabled':''}>Show a possible match</button><details><summary>Scoring & controls</summary><p>Each cleared treat earns 10 candy points × the cascade number. Reach each 1,000 points to level up. Candy points and learning XP are separate. Use Tab or arrow keys to reach a tile, then Enter or Space to select it.</p></details></div></div></section>`;}
function drawGame(){render();}
function bindGame(){document.getElementById('open-challenge')?.addEventListener('click',()=>{if(game.busy)return;game.quizOpen=true;render(true);});document.getElementById('close-challenge')?.addEventListener('click',()=>{game.quizOpen=false;render();document.getElementById('open-challenge')?.focus();});document.getElementById('board-hint')?.addEventListener('click',()=>{const pair=legalSwap(game.board);if(!pair)return;game.selected=pair[0];game.message=`Try row ${Math.floor(pair[0]/SIZE)+1}, column ${pair[0]%SIZE+1} with row ${Math.floor(pair[1]/SIZE)+1}, column ${pair[1]%SIZE+1}.`;drawGame();});app.querySelectorAll('[data-cell]').forEach(b=>{b.addEventListener('click',()=>selectCandy(Number(b.dataset.cell)));b.addEventListener('keydown',e=>{const i=Number(b.dataset.cell),delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-SIZE,ArrowDown:SIZE}[e.key];if(delta===undefined)return;e.preventDefault();const j=i+delta;if(j>=0&&j<SIZE*SIZE&&adjacent(i,j))app.querySelector(`[data-cell="${j}"]`)?.focus();});});}
async function selectCandy(i){if(game.busy||game.quizOpen||game.moves<=0)return;if(game.selected===null){game.selected=i;drawGame();app.querySelector(`[data-cell="${i}"]`)?.focus();return;}const first=game.selected;if(first===i){game.selected=null;drawGame();return;}if(!adjacent(first,i)){game.selected=i;game.message='Choose a treat directly beside this one.';drawGame();return;}game.selected=null;[game.board[first],game.board[i]]=[game.board[i],game.board[first]];if(!matchCells(game.board).length){[game.board[first],game.board[i]]=[game.board[i],game.board[first]];game.message='That swap makes no match. Try another—your move is safe.';drawGame();return;}game.moves--;game.swaps++;game.busy=true;const epoch=gameEpoch;let chain=0,total=0;while(true){const cells=matchCells(game.board);if(!cells.length)break;chain++;game.cleared=cells;const gain=cells.length*10*chain;game.points+=gain;total+=gain;game.message=chain>1?`Cascade ×${chain}! +${gain} candy points.`:`Sweet match! +${gain} candy points.`;drawGame();await new Promise(resolve=>setTimeout(resolve,matchMedia('(prefers-reduced-motion: reduce)').matches?0:240));if(epoch!==gameEpoch)return;for(const k of cells)game.board[k]=null;for(let c=0;c<SIZE;c++){const column=[];for(let r=SIZE-1;r>=0;r--)if(game.board[r*SIZE+c]!==null)column.push(game.board[r*SIZE+c]);while(column.length<SIZE)column.push(Math.floor(Math.random()*treats.length));for(let r=SIZE-1;r>=0;r--)game.board[r*SIZE+c]=column[SIZE-1-r];}game.cleared=[];if(chain>=30){game.board=newBoard();break;}}
 game.combo=chain;game.busy=false;game.message=`+${total} candy points${chain>1?` · ${chain} cascades`:''}. ${game.moves?'Keep matching!':'Answer another challenge to earn moves.'}`;if(!legalSwap(game.board)){game.board=newBoard();game.message+=' No matches remained, so the board was refreshed for free.';}drawGame();document.getElementById(game.moves?'board-hint':'open-challenge')?.focus();}
function awardMoves(correct,id){const reward=phase==='quest'?(correct?3:1):(correct&&!mastered.has(id)?2:0);game.moves+=reward;return reward;}
document.addEventListener('keydown',e=>{if(!game.quizOpen)return;if(e.key==='Escape'){game.quizOpen=false;render();document.getElementById('open-challenge')?.focus();return;}if(e.key==='Tab'){const modal=document.getElementById('challenge-dialog'),nodes=modal?.querySelectorAll('button:not(:disabled),input:not(:disabled),a[href],summary,[role=slider][tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===modal.querySelector('h1'))){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
